# Generated by Django 3.2.9 on 2022-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0024_contact_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.CharField(choices=[('default', 'На рассмотрении'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='default', max_length=30),
        ),
    ]
