# Generated by Django 3.2.9 on 2022-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0026_remove_about_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('default', 'На рассмотрении'), ('rasm', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='default', max_length=30),
        ),
    ]
