# Generated by Django 3.2.9 on 2022-04-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0029_auto_20220425_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
