# Generated by Django 3.2.9 on 2022-04-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0033_auto_20220425_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, upload_to='Lesson/images', verbose_name='Subject Image'),
        ),
    ]
