# Generated by Django 3.2.9 on 2022-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0036_lesson_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image2',
            field=models.ImageField(default='', upload_to='cart/images', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='cart',
            name='image3',
            field=models.ImageField(default='', upload_to='cart/images', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='cart',
            name='image4',
            field=models.ImageField(default='', upload_to='cart/images', verbose_name='Изображение4'),
        ),
    ]
