# Generated by Django 3.2.9 on 2022-04-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0037_auto_20220426_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image0',
            field=models.ImageField(default='', upload_to='cart/images', verbose_name='Изображение на главной'),
        ),
    ]
