# Generated by Django 3.2.9 on 2022-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehprime', '0038_cart_image0'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postavki',
        ),
        migrations.AlterField(
            model_name='cart',
            name='image1',
            field=models.ImageField(default='', upload_to='cart/images', verbose_name='Изображение 1'),
        ),
    ]
